const DUMMY_PATIENTS = [
  {
    id: 1,
    fullName: "Nada Aql",
    email: "nada.aql@gmail.com",
    phone: "+201008205312",
    age: 29,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 2,
    fullName: "Hazem Abdelmajid",
    email: "hazem.abdelmajid@gmail.com",
    phone: "+201012020766",
    age: 33,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    id: 3,
    fullName: "Hoda Bakry",
    email: "hoda.bakry@gmail.com",
    phone: "+201012020766",
    age: 59,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/34.jpg",
  },
  {
    id: 4,
    fullName: "Ola Ashour",
    email: "ola.ashour@gmail.com",
    phone: "+201122626940",
    age: 45,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    id: 5,
    fullName: "Hanaa Khalil",
    email: "hanaa.khalil@gmail.com",
    phone: "+201005521587",
    age: 37,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    id: 6,
    fullName: "Sajda Hafez",
    email: "sajda.hafez@gmail.com",
    phone: "+201006865699",
    age: 52,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/67.jpg",
  },
  {
    id: 7,
    fullName: "Mohamed Abdelkader",
    email: "mohamed.abdelkader@gmail.com",
    phone: "+201140092221",
    age: 30,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 8,
    fullName: "Tarek El-Moghawry",
    email: "tarek.moghawry@gmail.com",
    phone: "+201111269301",
    age: 60,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 9,
    fullName: "Reem Saleh",
    email: "reem.saleh@gmail.com",
    phone: "+201001842794",
    age: 48,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/78.jpg",
  },
  {
    id: 10,
    fullName: "Abdelmohsen Salem",
    email: "abdelmohsen.salem@gmail.com",
    phone: "+201003738387",
    age: 27,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
  },
  {
    id: 11,
    fullName: "Amjad Hussein",
    email: "amjad.hussein@gmail.com",
    phone: "+201090986990",
    age: 40,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/38.jpg",
  },
  {
    id: 12,
    fullName: "Sara Mohsen",
    email: "sara.mohsen@gmail.com",
    phone: "+201012345678",
    age: 31,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/89.jpg",
  },
  {
    id: 13,
    fullName: "Khaled Nour",
    email: "khaled.nour@gmail.com",
    phone: "+201198765432",
    age: 44,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    id: 14,
    fullName: "Mona Farouk",
    email: "mona.farouk@gmail.com",
    phone: "+201011223344",
    age: 38,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 15,
    fullName: "Ahmed Saber",
    email: "ahmed.saber@gmail.com",
    phone: "+201055667788",
    age: 55,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/59.jpg",
  },
  {
    id: 16,
    fullName: "Dina El-Sayed",
    email: "dina.elsayed@gmail.com",
    phone: "+201099887766",
    age: 26,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 17,
    fullName: "Omar Galal",
    email: "omar.galal@gmail.com",
    phone: "+201033445566",
    age: 34,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    id: 18,
    fullName: "Yasmin Taha",
    email: "yasmin.taha@gmail.com",
    phone: "+201077889900",
    age: 42,
    gender: "Female",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
  },
  {
    id: 19,
    fullName: "Mostafa Hamdy",
    email: "mostafa.hamdy@gmail.com",
    phone: "+201021343546",
    age: 50,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/82.jpg",
  },
  {
    id: 20,
    fullName: "Nour Eldin Hassan",
    email: "nour.hassan@gmail.com",
    phone: "+201087654321",
    age: 36,
    gender: "Male",
    image: "https://randomuser.me/api/portraits/men/93.jpg",
  },
];

export const ROWS_OPTIONS = [5, 10, 20, 50];
export default DUMMY_PATIENTS;
