export const PATIENTS_MOCK = [
  {
    id: 1,
    name: "Sara Kamel",
    age: 34,
    gender: "Female",
    visitType: "Online",
    chatExpired: "3 days left",
    riskLevel: "Low",
    bloodPressure: "Normal",
    lastVisitLabel: "2 days ago",
    lastVisitKey: "this-week",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=80&q=80",
    canOpenChat: false,
    vitals: {
      heartRate: 72,
      bloodPressure: "120/80",
      bloodSugar: 95,
      cholesterol: 180,
      bloodCount: "Normal",
    },
    medicalRecords: [
      {
        id: "r-1-1",
        fileName: "Complete Blood Count",
        type: "Blood Test",
        uploadDate: "Oct 28, 2024",
      },
      {
        id: "r-1-2",
        fileName: "Chest X-Ray",
        type: "Radiology",
        uploadDate: "Oct 25, 2024",
      },
      {
        id: "r-1-3",
        fileName: "Lipid Panel",
        type: "Blood Test",
        uploadDate: "Oct 20, 2024",
      },
    ],
    qrCode:
      "https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=PulseX-Patient-Sara-Kamel",
    generatedOn: "19/10/2024",
    totalFiles: 8,
  },
  {
    id: 2,
    name: "Ali Mohamed",
    age: 45,
    gender: "Male",
    visitType: "Online",
    chatExpired: "1 day left",
    riskLevel: "High",
    bloodPressure: "High",
    lastVisitLabel: "1 week ago",
    lastVisitKey: "this-week",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&q=80",
    canOpenChat: false,
    vitals: {
      heartRate: 78,
      bloodPressure: "135/88",
      bloodSugar: 112,
      cholesterol: 195,
      bloodCount: "Normal",
    },
    medicalRecords: [
      {
        id: "r-2-1",
        fileName: "ECG Report",
        type: "Radiology",
        uploadDate: "Nov 02, 2024",
      },
      {
        id: "r-2-2",
        fileName: "Cardiac Enzymes",
        type: "Blood Test",
        uploadDate: "Oct 30, 2024",
      },
    ],
    qrCode:
      "https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=PulseX-Patient-Ali-Mohamed",
    generatedOn: "21/10/2024",
    totalFiles: 6,
  },
  {
    id: 3,
    name: "Yousra Adel",
    age: 28,
    gender: "Female",
    visitType: "Clinic",
    chatExpired: "Open Chat",
    riskLevel: "Moderate",
    bloodPressure: "Normal",
    lastVisitLabel: "Today",
    lastVisitKey: "today",
    avatar:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=80&q=80",
    canOpenChat: true,
    vitals: {
      heartRate: 74,
      bloodPressure: "118/76",
      bloodSugar: 92,
      cholesterol: 176,
      bloodCount: "Normal",
    },
    medicalRecords: [
      {
        id: "r-3-1",
        fileName: "HbA1c",
        type: "Blood Test",
        uploadDate: "Oct 28, 2024",
      },
      {
        id: "r-3-2",
        fileName: "Abdominal Ultrasound",
        type: "Radiology",
        uploadDate: "Oct 25, 2024",
      },
      {
        id: "r-3-3",
        fileName: "Liver Function Test",
        type: "Blood Test",
        uploadDate: "Oct 20, 2024",
      },
    ],
    qrCode:
      "https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=PulseX-Patient-Yousra-Adel",
    generatedOn: "19/10/2024",
    totalFiles: 8,
  },
  {
    id: 4,
    name: "Waled Omar",
    age: 52,
    gender: "Male",
    visitType: "Online",
    chatExpired: "2 days left",
    riskLevel: "Low",
    bloodPressure: "Normal",
    lastVisitLabel: "3 days ago",
    lastVisitKey: "this-week",
    avatar:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&q=80",
    canOpenChat: false,
    vitals: {
      heartRate: 80,
      bloodPressure: "128/84",
      bloodSugar: 108,
      cholesterol: 188,
      bloodCount: "Normal",
    },
    medicalRecords: [
      {
        id: "r-4-1",
        fileName: "Lung CT",
        type: "Radiology",
        uploadDate: "Oct 18, 2024",
      },
      {
        id: "r-4-2",
        fileName: "Complete Blood Count",
        type: "Blood Test",
        uploadDate: "Oct 15, 2024",
      },
    ],
    qrCode:
      "https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=PulseX-Patient-Waled-Omar",
    generatedOn: "14/10/2024",
    totalFiles: 5,
  },
  {
    id: 5,
    name: "Soha Ali",
    age: 39,
    gender: "Female",
    visitType: "Clinic",
    chatExpired: "3 days left",
    riskLevel: "Moderate",
    bloodPressure: "Elevated",
    lastVisitLabel: "1 day ago",
    lastVisitKey: "today",
    avatar:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=80&q=80",
    canOpenChat: false,
    vitals: {
      heartRate: 76,
      bloodPressure: "124/82",
      bloodSugar: 102,
      cholesterol: 182,
      bloodCount: "Normal",
    },
    medicalRecords: [
      {
        id: "r-5-1",
        fileName: "Lipid Panel",
        type: "Blood Test",
        uploadDate: "Oct 22, 2024",
      },
      {
        id: "r-5-2",
        fileName: "Pelvic Ultrasound",
        type: "Radiology",
        uploadDate: "Oct 19, 2024",
      },
    ],
    qrCode:
      "https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=PulseX-Patient-Soha-Ali",
    generatedOn: "11/10/2024",
    totalFiles: 4,
  },
  {
    id: 6,
    name: "Hossam Saad",
    age: 41,
    gender: "Male",
    visitType: "Clinic",
    chatExpired: "4 days left",
    riskLevel: "High",
    bloodPressure: "High",
    lastVisitLabel: "2 weeks ago",
    lastVisitKey: "older",
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=80&q=80",
    canOpenChat: false,
    vitals: {
      heartRate: 84,
      bloodPressure: "140/92",
      bloodSugar: 120,
      cholesterol: 210,
      bloodCount: "Normal",
    },
    medicalRecords: [
      {
        id: "r-6-1",
        fileName: "Cardiac Stress Test",
        type: "Radiology",
        uploadDate: "Oct 12, 2024",
      },
      {
        id: "r-6-2",
        fileName: "Troponin Test",
        type: "Blood Test",
        uploadDate: "Oct 10, 2024",
      },
    ],
    qrCode:
      "https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=PulseX-Patient-Hossam-Saad",
    generatedOn: "08/10/2024",
    totalFiles: 5,
  },
];

export const getPatientById = (id) =>
  PATIENTS_MOCK.find((patient) => String(patient.id) === String(id));
